#!/bin/bash
cd functions

for dir in *; do
    echo "zipping '$dir'"
    cd $dir
        zip -r function.zip *.py
        aws lambda update-function-code --function-name $dir --zip-file fileb://function.zip
        rm function.zip
    cd ..
done

cd ..
