#!/bin/bash
cd functions

for dir in *; do
    echo "zipping '$dir'"
    cd $dir
        abs_dir=$(pwd)

        cd venv/lib/python3.8/site-packages/
        zip -r9 "$abs_dir/function.zip" .

        cd $abs_dir
        zip -g function.zip *.py
    cd ..
done

cd ..
