AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Description: >
  CFC Nanny

  performs actions on cfc game servers

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Parameters:
  NannySSHPrivateKey:
    Description: Required. The ssh private key to use for ssh lambda actions
    Type: AWS::SSM::Parameter::Value<String>
    Default: 'NannySSHPrivateKey'

  NannyAuthJsonEnv:
    Description: Required. json data defining the auth environments
    Type: AWS::SSM::Parameter::Value<String>
    Default: 'NannyAuthJsonEnv'

Globals:
  Function:
    Timeout: 60
    Runtime: python3.8

_shared:
  restart: &restart_defaults
    CodeUri: src/gmod_restart/
    Handler: app.lambda_handler
    Layers:
      - !Ref RestartDepLayer

Resources:
  NannyApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      Auth:
        DefaultAuthorizer: NannyRequestAuthorizer
        Authorizers:
          NannyRequestAuthorizer:
            FunctionArn: !GetAtt CFCNannyAuthFunction.Arn
            Identity:
              Headers:
                - Authorization
            AuthorizerPayloadFormatVersion: 2.0
            EnableSimpleResponses: true

  # auth
  CFCNannyAuthFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/cfc_nanny_auth/
      Handler: authorizer.handler
      Environment:
        Variables:
          JSON_ENV: !Ref NannyAuthJsonEnv

  # Functions
  CFCTestRestartFunction:
    Type: AWS::Serverless::Function
    Properties:
      <<: *restart_defaults
      Environment:
        Variables:
          private_key: !Ref NannySSHPrivateKey
          SERVER_DIR: "/var/steam/gmod/cfc-test/"
          SEVER_NAME: "cfctest"
      Events:
        CFCTestRestart:
          Type: HttpApi
          Properties:
            ApiId: !Ref NannyApi
            Path: /cfctest-restart
            Method: post


  CFC3RestartFunction:
    Type: AWS::Serverless::Function
    Properties:
      <<: *restart_defaults
      Environment:
        Variables:
          private_key: !Ref NannySSHPrivateKey
          SERVER_DIR: "/var/steam/gmod/cfc3/"
          SERVER_NAME: "cfc3"
      Events:
        CFC3Restart:
          Type: HttpApi
          Properties:
            ApiId: !Ref NannyApi
            Path: /cfc3-restart
            Method: post

  RestartDepLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: nanny-restart-dependencies
      Description: Dependencies for cfc nanny restart
      ContentUri: layers/restart_dependencies
      CompatibleRuntimes:
        - python3.8
      RetentionPolicy: Retain
    Metadata:
      BuildMethod: makefile
